version: 2
jobs:
  build_test:
    docker:
      - image: quay.io/token/go-build:v0.3.4
    working_directory: /home/circleci/github.com/tokencard/ethertest
    steps:
      - checkout
      - restore_cache:
          keys:
          - vendor-{{ checksum "go.sum" }}
      - run: go mod vendor
      - run: go test -v ./...
      - save_cache:
          key: vendor-{{ checksum "go.sum" }}
          paths:
            - "vendor"
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_test:
          filters:
            tags:
              ignore: ""
